name: Rust Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  run-tests-and-coverage:
    uses: fermi-ad/.github/.github/workflows/rust-deployment.yaml@v1
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write

# If using a git submodule, add 
#    with:
#      pull-git-submodules: true

# If using an internal git repo as a Rust dependency, add
#    with:
#      references-internal-git-repo: true
