name: Rust Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests-and-coverage:
    uses: fermi-ad/.github/.github/workflows/rust-integration.yaml@ccc0401ba36fba7dd1854286c5f2857e51babd70
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
