name: Rust Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests-and-coverage:
    uses: fermi-ad/.github/.github/workflows/rust-integration.yaml@v1
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write

# If there are extra files to ignore during code coverage reporting, add
#    with:
#      coverage-exclude: '<The filename patterns to exclude, must begin with a pipe "|" character!>'

# If using a git submodule, add 
#    with:
#      pull-git-submodules: true

# If using an internal git repo as a Rust dependency, add
#    with:
#      references-internal-git-repo: true
