name: Notify template usage

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  notify-template-usage:
    uses: fermi-ad/.github/.github/workflows/notify-template-usage.yml@v1
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
